apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: star
  template:
    metadata:
      labels:
        app: star
    spec:
      containers:
      - name: star
        image: tiwafuchi/clarity-starwars:V01
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 1; nginx -s quit; sleep 3"]
